<a href="https://colab.research.google.com/github/garvjain7/Chatbot/blob/main/Day_3_Poornima_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
zeros_array = np.zeros((1,2,3) , dtype = int)
zeros_array

array([[[0, 0, 0],
        [0, 0, 0]]])

In [ ]:
# Creating one array
# (block, row, column) = (2,4,7)
ones_array = np.ones((2,4,7) , dtype = int)
ones_array

array([[[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]]])

In [ ]:
ones_array[1][0][2] = 8
ones_array

array([[[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 8, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]]])

In [ ]:
#
ones_array[1][3][6] = 6
ones_array

array([[[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 8, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 6]]])

In [ ]:
# get an array from 4 to 20 with difference of 4 in two consecutive numbers
array1 = np.arange(4,21,4)
array1

array([ 4,  8, 12, 16, 20])

In [ ]:
even = np.arange(1,21,2)
even

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
# Find 7 number between 5 and 25
array2 = np.linspace(5,25,7)
array2

array([ 5.        ,  8.33333333, 11.66666667, 15.        , 18.33333333,
       21.66666667, 25.        ])

In [ ]:
even = np.arange(1,21,2)
type(even)

numpy.ndarray

In [ ]:
# date feeded in a form of an array
price_array = np.array([10000,20000,50000,16000,12000,17000,12000,9000,12000,7000])
qty_array = np.array([4,12,20,15,18,13,12,7,12,15])
print(price_array)
print(qty_array)

[10000 20000 50000 16000 12000 17000 12000  9000 12000  7000]
[ 4 12 20 15 18 13 12  7 12 15]


In [ ]:
# total inventory value of data
price_per_mobile = price_array * qty_array
print(price_per_mobile)
np.sum(price_per_mobile)

[  40000  240000 1000000  240000  216000  221000  144000   63000  144000
  105000]


2413000

In [ ]:
# to find the average price of the mobile
print(np.average(price_array))
# to find the maximum price of phone
print(np.max(price_array))


16500.0
50000
1
1
1
1
3
3
3
3
3
3


In [ ]:
# to find the mode of all the prices of mobile phones
''' Convert array to list
    Create a empty list and apply for loop
    inside the for loop counts the value then append them in to empty list
    Convert to array
    Find maximum '''
price_array = list(price_array)
count = []
for i in range(0, 10):
  v = price_array.count(price_array[i])
  count.append(v)
np.max(count)

3

In [ ]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distribut

In [ ]:
import pandas as pd
