<a href="https://colab.research.google.com/github/garvjain7/Chatbot/blob/main/matplotlib_graph.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# this is the file to generate some graph using nupmy and matloptlib to some data or array

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
array_1d = np.arange(12)
array_2d = array_1d.reshape(3,4)
array_3d = array_1d.reshape(2,3,2)
print(array_1d)
print(array_2d)
print(array_3d)

In [9]:
fig, axes = plt.subplots(1, 3, figsize=(15,5))
axes[0].imshow(array_1d.reshape(1, -1), cmap='Blues', aspect='auto')
axes[0].set_title('1D Array')
axes[1].imshow(array_2d, cmap='Oranges', aspect='auto')
axes[1].set_title('2D Array')
axes[2].imshow(array_3d.reshape(3,4), cmap='Purples', aspect='auto')
axes[2].set_title('3D Array')

for ax in axes:
    ax.axis('off')
    plt.tight_layout()
    plt.savefig('array_examples.png')
plt.show()

In [14]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
fig, axes = plt.subplots(figsize=(6,6))
for i, row in enumerate(array_2d):
    ax.plot(row, marker='o', linestyle='-', label=f'Row{i+1}', color=colors[i])
plt.show()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
