<a href="https://colab.research.google.com/github/garvjain7/Chatbot/blob/main/VAC_4th_sem_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Advance functions in python
# Lambda function -> it is a one line function or anonymus function which takes another function as input

square = lambda n:n**2
l=[12,14,13,15,16,17,18]
new_list1 = list(map(lambda n:n**2,l))
print(new_list1)

[144, 196, 169, 225, 256, 289, 324]


In [5]:
add = lambda a,b:a+b
print(add(12,3))

# finding the maximum number
# 1.) by normal function
def max(a,b):
  if a>b:
    return a
  else:
    return b

#2.) by lambda function(This functions are like inline function of C and C++)
max = lambda a,b:a if a>b else b
print(max(12,15))

15


In [8]:
# reduce -> reduce is a high order function and it is the way of aggregate a sequence of value into a single vlaue by repeatedly
# we cannot use reduce directly we have to import it from functools library
from functools import reduce

# reduce function with lambda function
l1 = [2,4,6,8,10]
func = reduce(lambda x,y : x+y, l1)
print(func)

# reduce function without lambda function
# Define a normal function
def add(x, y):
    return x + y

# Use reduce with the normal function
numbers = [1, 2, 3, 4, 5]
sum_numbers = reduce(add, numbers)

print(sum_numbers)

# Types of reduce() Applications
# 2.1 Product of All Numbers
product = reduce(lambda x, y: x * y, [1, 2, 3, 4, 5])
print(product)  # Output: 120

# 2.2 Finding Maximum Element
numbers = [5, 3, 8, 2, 9, 1]
max_value = reduce(lambda x, y: x if x > y else y, numbers)
print(max_value)  # Output: 9

# 2.3 Finding GCD (Greatest Common Divisor)
import math
gcd_value = reduce(math.gcd, [48, 64, 32, 16])
print(gcd_value)  # Output: 16

# 2.4 Concatenating Strings
words = ["Hello", "World", "Python"]
sentence = reduce(lambda x, y: x + " " + y, words)
print(sentence)  # Output: Hello World Python

# 2.5 Using an Initial Value
numbers = [1, 2, 3, 4]
result = reduce(lambda x, y: x * y, numbers, 10)  # Initial value = 10
print(result)  # Output: 240 (10 * 1 * 2 * 3 * 4)

15


In [26]:
# LEARNING ESSENTIAL LIBRARIES LIKE NUMPY(mathematical operation), PANDAS(data manipulation), MATPLOTLIB(visualization of data), SEABON
import numpy as np
l1 = np.array([11,12,13])
l2 = np.array([11,2,3])
print(l1 + l2)
print(type(l1))
# a = l1 + l2 # it can combine both the list because the default data value is taken as string

arr3 = np.array([[11,65,43,14],[11,28,64,22]])
arr4 = np.array([[11,12,92,34],[11,42,22,2]])
print(arr3)

print(arr3.shape) # rows and columns
print(arr3.size) # numbers of element
print(arr3.ndim) # dimenssion of array
print(len(arr3)) # length of the array
print(arr3.dtype) # datatype of array
print(arr3.astype(int)) # conversion of data type
print(arr3.astype(str)) # conversion of data type
print(arr3 + arr4)

[22 14 16]
<class 'numpy.ndarray'>
[[11 65 43 14]
 [11 28 64 22]]
(2, 4)
8
2
2
int64
[[11 65 43 14]
 [11 28 64 22]]
[['11' '65' '43' '14']
 ['11' '28' '64' '22']]
[[ 22  77 135  48]
 [ 22  70  86  24]]


In [27]:
sq = np.sort(arr3)
print(sq)

[[11 14 43 65]
 [11 22 28 64]]


In [44]:
# combining and spliting array
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[11,22,22],[22,21,23]])
print(np.concatenate([a,b]))
print("\n")
print(np.concatenate([a,b], axis=1)) # concatenates the values horizontally
print("\n")
print(np.concatenate([a,b], axis=0)) # concatenates the values vertically
print("\n")

# using hstack
print(np.hstack([a,b]))
print("\n")

# using vstack
print(np.vstack([a,b]))
print("\n")

a1 = np.array([11,12,13,14,15,16,17,18,19])
a2 = np.array_split(a1,3) # array_split aso works with unequal parts. If the array has not enough rows that it creates an empty array.
print(a2)
print("\n")

a4 = np.split(a1,3) # split works on equal size array i.e. in which array musy be divided into equal parts. It does not create empty array.`
print(a4)
print("\n")

a3 = np.array_split(a,3)
print(a3)

[[ 1  2  3]
 [ 4  5  6]
 [11 22 22]
 [22 21 23]]


[[ 1  2  3 11 22 22]
 [ 4  5  6 22 21 23]]


[[ 1  2  3]
 [ 4  5  6]
 [11 22 22]
 [22 21 23]]


[[ 1  2  3 11 22 22]
 [ 4  5  6 22 21 23]]


[[ 1  2  3]
 [ 4  5  6]
 [11 22 22]
 [22 21 23]]


[array([11, 12, 13]), array([14, 15, 16]), array([17, 18, 19])]


[array([11, 12, 13]), array([14, 15, 16]), array([17, 18, 19])]


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]


In [48]:
# sorting with 2d array
# aa = np.array([[1,4,22,3,2],[22,44,122,22,11]])
# sa = np.sort(aa)
# print(sa)

# searching
# aa = np.array([1,4,22,3,222,44,122,22,11])
# ss = np.where(aa == 22)
# print(ss)

(array([2, 7]),)


In [50]:
arr = np.array([20,40,70,60])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.size(arr))
print(np.cumsum(arr))
print(np.cumproduct(arr))

190
20
70
4
[ 20  60 130 190]
[     20     800   56000 3360000]


In [53]:
price=[100,150,200,300]
quantity=[10,3,5,12]
price = np.array(price)
quantity = np.array(quantity)
total = np.cumprod([price,quantity], axis=0) # cumprod can product the elements of two array index wise
print(total)

[[ 100  150  200  300]
 [1000  450 1000 3600]]


In [57]:
import statistics as st
baked_food = [200,210,220,190,180,110,320,200,210,210]
a = np.array(baked_food)
print(np.mean(baked_food)) # find the mean
print(np.median(baked_food)) # find the median
print(st.mode(baked_food)) # find the mode. Mode is the function of statistics library/module

205.0
205.0
210


In [59]:
# correlation coefficient using numpy
# -1 represent inversely propotional relationship
# 1 represent propotional relationship
# 0 means no relationship

# alcohol_consumption = [30,50,60,70,80]
# deaths = [10,13,15,17,19]
# print(np.corrcoef(alcohol_consumption,deaths))

# Example data
marketing_spend = [5000, 7000, 8000, 12000, 15000]  # X1: Marketing spend in $
discounts = [10, 15, 20, 25, 30]  # X2: Discounts in %
sales_revenue = [20000, 25000, 27000, 30000, 32000]  # Y: Sales revenue in $

# Calculate correlation matrix
corr_matrix = np.corrcoef([marketing_spend, discounts, sales_revenue])

# Print correlation matrix
print(corr_matrix)

[[1.         0.97907556 0.94910563]
 [0.97907556 1.         0.98432414]
 [0.94910563 0.98432414 1.        ]]


In [69]:
import pandas as pd
df = pd.read_csv('hotel-booking-data.txt', delimiter="\t")
df.head()

Date Company        Person Name  Room number
0  1-Jan-2022  Avamba  Anatole Ridehalgh       4008.0
1  1-Jan-2022    Fatz    Aldrich McKevin       2002.0
2  1-Jan-2022   Leexo    Stanley Hadrill       4012.0
3      Hotels     NaN                NaN          NaN
4  1-Jan-2022  Rhyzio       Lyndell Tice       1006.0